version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "phanect"
    groups:
      security:
        applies-to: "security-updates"
        patterns:
          - "*"
      normal:
        applies-to: "version-updates"
        patterns:
          - "*"
